### ISSUE TITLE
No Script File 

### ISSUE THREAD

**Issue by johndalloxx** [MackinnonBuck/blazor-page-script#1]
Hey I cant seem to get this to work. Im doing everything in the setup, although my Program.cs file has some more things to it: 

```var builder = WebApplication.CreateSlimBuilder(args);

// Add services to the container.
builder.Services.AddRazorComponents().AddInteractiveServerComponents();

builder.Services.AddHttpContextAccessor();
builder.Services.AddDistributedMemoryCache();
builder.Services.AddAntiforgery();

var app = builder.Build();

// Configure the HTTP request pipeline.
if (!app.Environment.IsDevelopment())
{
    app.UseExceptionHandler("/Error", createScopeForErrors: true);
    // The default HSTS value is 30 days. You may want to change this for production scenarios, see https://aka.ms/aspnetcore-hsts.
    app.UseHsts();
}

app.UseStaticFiles();
app.UseAntiforgery();

app.MapRazorComponents<App>().AddInteractiveServerRenderMode();

app.Run();

```

I there anything in here that might interfer with how this package works?

DOM looks like this: 
<img width="540" alt="Skjermbilde 2023-12-13 kl  23 41 38" src="https://github.com/MackinnonBuck/blazor-page-script/assets/99718201/b6037f89-578d-4300-87b9-08f2744448f5">

Home.razor file: 
```
@page "/"

<PageTitle>Home</PageTitle>
<PageScript Src="./Components/Pages/Home.razor.js" />
<h1 class="text-sm text-blue-800 m-auto w-fit z-10">
    Home
</h1>
```
Home.razor.js:

```
// Called when the script first gets loaded on the page.
export function onLoad() {
    console.log('Load');
}

// Called when an enhanced page update occurs, plus once immediately after
// the initial load.
export function onUpdate() {
    console.log('Update');
}

// Called when an enhanced page update removes the script from the page.
export function onDispose() {
    console.log('Dispose');
}

```

**Comment by johndalloxx** [comment]
Tried to clone project as well, doesn't work.

**Comment by MackinnonBuck** [comment]
Hm, looks fine to me. Some questions:

1. How are you getting the `<PageScript />` component into your app? Are you consuming the NuGet package or copying the source code into your project?
2. Are there any errors in the console? That might point to the problem.

If you could link to a minimal repro project hosted as a GitHub repository, I would be able to look into it more to find out what's going on. Thanks!

**Comment by MackinnonBuck** [comment]
Closing this out since I haven't heard back in a while. If you can trace the problem back to an issue with the library, please feel free to open a new issue. Thanks!
