### ISSUE TITLE
Issue with PageScript, OutputCache, and Navigating to #Element in Blazor SSR

### ISSUE THREAD

**Issue by zubairkhakwani** [MackinnonBuck/blazor-page-script#12]
Initially, everything functions as expected. However, upon adding the OutputCache attribute, two significant issues arise

1. **Script Functionality Breakdown:** Upon revisiting the cached Home page, script functionality becomes non-responsive. Despite logging within the OnUpdate method, the console remains empty, indicating a failure in executing JavaScript functionality. This impedes the user experience and disrupts the intended behavior of the page.
2. **Excessive Reloading with Hash Navigation** Furthermore, when navigating to a link within the same page containing a hash (#element), Blazor's JavaScript file (blazor.web.js) inexplicably reloads the page multiple times. 

If I remove `@attribute [OutputCache(Duration = 2000)]` it works fine.

i have also created the issue in aspnetcore repository as it might be issue with caching and not PageScript.

[minimalistic project which reproduces this issue](https://github.com/zubairkhakwani/BlazorCacheIssue)

Additionally, I've created a Video demonstrating the precise steps to replicate the issues.

https://github.com/MackinnonBuck/blazor-page-script/assets/38009549/8473730d-a680-461d-9c1a-5ac034fffe8d

**Comment by MackinnonBuck** [comment]
Hi @zubairkhakwani,

It looks like there's more than one problem than the `PageScript` issue you're seeing. I also see you opened an issue [here](https://github.com/dotnet/aspnetcore/issues/55534), so let's use that to track the issue.

I noticed that your repro project utilizes top-level interactivity (and thus interactive routing). Please note that this isn't currently supported in `PageScript`. I'm using #11 to track adding support for that.

I'm going to close this out now. I appreciate the feedback!
